on:
  workflow_dispatch:  
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  TARGET: KOBO
jobs:
  compile-xcsoar-${{ env.TARGET }}:
    runs-on: ubuntu-latest
    steps:
     - id: checkout 
       uses: actions/checkout@v2
       with:
         submodules: True
     - id: cache-ccache
       uses: hendrikmuhs/ccache-action@v1
       with:
         key: ${{ matrix.os }}-${{ matrix.type }}-${{ env.TARGET }}
     - id: repository
       uses: ASzc/change-string-case-action@v1
       with:
         string: ${{ github.repository }}
     - name: XCSoar Compile ${{ env.TARGET }} 
       uses: addnab/docker-run-action@v3
       with:
         image: ghcr.io/${{ steps.repository.outputs.lowercase }}/xcsoar-build:latest
         options: -v ${{ github.workspace }}:/opt/xcsoar -v /home/runner/work/XCSoar/XCSoar/.ccache:/root/.ccache
         run: | 
           cd /opt/xcsoar
           xcsoar-compile ${{ env.TARGET }} USE_CCACHE=y V=2 everything
     - name: XCSoar run checks
       uses: addnab/docker-run-action@v3
       with:
         image: ghcr.io/${{ steps.repository.outputs.lowercase }}/xcsoar-build:latest
         options: -v ${{ github.workspace }}:/opt/xcsoar -v /home/runner/work/XCSoar/XCSoar/.ccache:/root/.ccache
         run: | 
           cd /opt/xcsoar
           xcsoar-compile ${{ env.TARGET }} V=2 check
